# Generated by Django 5.1.2 on 2024-11-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
