# Generated by Django 5.1.2 on 2024-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
