# Generated by Django 5.1.2 on 2024-11-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='images',
            field=models.CharField(default='https://orderapp-static.burgerkingrus.ru/x256/mobile_image/7d5a965ff6212dc44bc39fe635e32d47.webp', max_length=250),
            preserve_default=False,
        ),
    ]
